#ifndef _BACKEND_LATTICE_H_
#define _BACKEND_LATTICE_H_


/* Some backends need specialized lattice data
 * in loops. These are implemented here.
 * Loops generated by Transformer can access
 * this through lattice->backend_lattice.
 */
struct backend_lattice_struct {
  void setup(lattice_struct lattice){}
};

#endif