name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - documentation
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir ./docs/html
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: documentation
          folder: docs/html
          config_file: docs/config