name: Deploy singularity container to github release page under nightly release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build:
        description: 'Build the singularity container'

jobs:
  build_release:
    if: "github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'GENERATE SINGULARITY')" 
    name: build_nightly_release
    runs-on: ubuntu-22.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      # Install singularity from cached deb or download if missing
      - name: Install Singularity
        run: |
          sudo apt-get install singularity-container
          singularity --version

      # Build the container separately
      - name: Build singularity container
        run: |
          cd singularity
          sudo singularity build hilapp-arm.sif hilapp_local.def
          cd ..
          ls -lh ./singularity/hilapp-arm.sif

      - name: Upload SIF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hilapp-arm-sif
          path: ./singularity/hilapp-arm.sif

      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: Nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./singularity/hilapp-arm.sif
