name: Deploy singularity container to github release page under nightly release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build:
        description: 'Build the apptainer container'

jobs:
  build_arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build ARM SIF
        run: |
          sudo apt-get update
          sudo apt-get install -y containernetworking-plugins
          wget http://ftp.de.debian.org/debian/pool/main/a/apptainer/apptainer_1.4.2-1_arm64.deb
          sudo dpkg -i apptainer_1.4.2-1_arm64.deb
          cd singularity
          sudo apptainer build hilapp-arm.sif hilapp_local.def
          cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: hilapp-arm-sif
          path: ./singularity/hilapp-arm.sif

  release:
    runs-on: ubuntu-latest
    needs: build_arm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: hilapp-arm-sif
          path: ./singularity/
      - name: Publish Nightly Release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: Nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./singularity/hilapp-arm.sif
          snapshots: true
